title: Subject Matter Authoring Using Jupyter Notebooks
author: Tony Hirst
copyright: "2018-2021" 
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 60  
parse:
  myst_dmath_double_inline: true

sphinx:
  html_copy_source: false
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  mermaid_version: 8.13.3
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.wavedrom
    - sphinxcontrib.plantuml
    - sphinxcontrib.tikz
    - sphinxcontrib.blockdiag